# Generated by Django 6.0.7 on 2026-07-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpoint',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='type',
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='is_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='is_exit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='order',
            field=models.PositiveIntegerField(default=3, unique=True),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='checkpoint',
            table='checkpoints',
        ),
    ]
