# Generated by Django 6.0.7 on 2026-07-13 14:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('CNIB', 'CNIB'), ('PASSPORT', 'Passeport')], max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('expired_date', models.DateField()),
                ('issue_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nationality', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
                'db_table': 'Visitors',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
