# Generated by Django 6.0.7 on 2026-07-14 08:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('CREATE_VISIT', "Création d'une visite"), ('VALIDATE_CHECKPOINT', "Validation d'un poste"), ('GENERATE_QR_CODE', 'Génération du QR Code'), ('SCAN_QR_CODE', 'Scan du QR Code'), ('ISSUE_BADGE', 'Remise du badge'), ('RETURN_BADGE', 'Retour du badge'), ('RETAIN_DOCUMENT', 'Consignation de la pièce'), ('RETURN_DOCUMENT', 'Restitution de la pièce'), ('COMPLETE_VISIT', 'Fin de la visite'), ('ACTIVATE_USER', "Activation d'un utilisateur"), ('DEACTIVATE_USER', "Désactivation d'un utilisateur")], max_length=50)),
                ('entity', models.CharField(choices=[('USER', 'Utilisateur'), ('ROLE', 'Rôle'), ('VISITOR', 'Visiteur'), ('VISIT', 'Visite'), ('WORKFLOW', 'Workflow'), ('WORKFLOW_STEP', 'Étape du workflow'), ('CHECKPOINT', 'Poste de contrôle'), ('QR_CODE', 'QR Code'), ('BADGE', 'Badge')], max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
