# Generated by Django 6.0.7 on 2026-07-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowstep',
            options={'ordering': ['step_order']},
        ),
        migrations.RenameField(
            model_name='workflowstep',
            old_name='order',
            new_name='step_order',
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'step_order')},
        ),
    ]
