# Generated by Django 6.0.7 on 2026-07-13 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_alter_checkpoint_options_remove_checkpoint_type_and_more'),
        ('workflow', '0002_alter_workflowstep_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='checkpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to='validation.checkpoint'),
        ),
        migrations.AlterModelTable(
            name='workflowstep',
            table='workflow_steps',
        ),
    ]
