# Generated by Django 6.0.7 on 2026-07-13 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitors', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateTimeField()),
                ('purpose', models.TextField()),
                ('host_name', models.CharField(max_length=255)),
                ('host_department', models.CharField(max_length=255)),
                ('host_email', models.EmailField(max_length=254)),
                ('host_phone', models.CharField(max_length=20)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.visitor')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflow')),
            ],
            options={
                'db_table': 'Visit',
                'ordering': ['-visit_date'],
            },
        ),
    ]
