# Generated by Django 6.0.7 on 2026-07-14 08:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
        ('visits', '0001_initial'),
        ('workflow', '0003_alter_workflowstep_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-entry_time'], 'verbose_name': 'Visite', 'verbose_name_plural': 'Visites'},
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='host_department',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='host_name',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='host_email',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='host_phone',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='visit',
            name='badge_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='document_retained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visit',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Créée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='visitors.visitor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='workflow.workflow'),
        ),
        migrations.AlterModelTable(
            name='visit',
            table='visits',
        ),
    ]
